/**
 * Core domain model for Canvas workflows.
 *
 * These types describe a workflow as the product understands it, and are
 * deliberately independent of any rendering library (including
 * `@xyflow/react`). Adapters map between this model and view-layer shapes.
 */

/** Identifier of a {@link Workflow}. */
export type WorkflowId = string;

/** Identifier of a {@link WorkflowNode}, unique within its workflow. */
export type WorkflowNodeId = string;

/** Identifier of a {@link WorkflowEdge}, unique within its workflow. */
export type WorkflowEdgeId = string;

/** ISO 8601 timestamp, e.g. `"2026-08-19T21:05:00.000Z"`. */
export type IsoDateString = string;

/** The kind of work a node performs. */
export type NodeType = "trigger" | "action" | "condition";

/** A point on the canvas, in workflow coordinate space. */
export interface NodePosition {
  x: number;
  y: number;
}

/**
 * Configuration specific to each node type.
 *
 * `samplePayload` is raw JSON text, not a parsed value: it's edited freely
 * in a textarea (see Inspector.tsx), and a mid-edit value like `{"a":` has
 * to stay representable without being rejected. It's parsed only when a
 * run actually needs it (see domain/execution.ts), falling back to `{}` on
 * invalid or absent JSON -- a trigger with no sample data configured yet
 * is a normal state, not an error.
 */
export type TriggerConfig =
  | { kind: "event"; event: string; samplePayload?: string }
  | { kind: "schedule"; cron: string; samplePayload?: string }
  | { kind: "form_submission"; formName: string; samplePayload?: string };

/** Every {@link TriggerConfig} variant, keyed by its `kind` tag. */
export type TriggerConfigKind = TriggerConfig["kind"];

/** Every value {@link TriggerConfigKind} allows, in display order. */
export const TRIGGER_CONFIG_KINDS: readonly TriggerConfigKind[] = [
  "event",
  "schedule",
  "form_submission",
];

export type ActionConfig =
  | { kind: "send_email"; recipient?: string }
  | { kind: "http_request"; url: string; method: "GET" | "POST" }
  | { kind: "add_tag"; tag: string }
  | { kind: "slack_message"; channel: string; message: string };

/** Every {@link ActionConfig} variant, keyed by its `kind` tag. */
export type ActionConfigKind = ActionConfig["kind"];

/** Every value {@link ActionConfigKind} allows, in display order. */
export const ACTION_CONFIG_KINDS: readonly ActionConfigKind[] = [
  "send_email",
  "http_request",
  "add_tag",
  "slack_message",
];

/** The comparisons a Condition node's branch can test for. */
export type ConditionOperator =
  | "equals"
  | "not_equals"
  | "contains"
  | "greater_than"
  | "less_than";

/** Every value {@link ConditionOperator} allows, in display order. */
export const CONDITION_OPERATORS: readonly ConditionOperator[] = [
  "equals",
  "not_equals",
  "contains",
  "greater_than",
  "less_than",
];

export interface ConditionConfig {
  field: string;
  operator: ConditionOperator;
  value: string;
}

/** Which output of a Condition node an edge leaves from. */
export type ConditionBranch = "true" | "false";

/** Every value {@link ConditionBranch} allows, in display order. */
export const CONDITION_BRANCHES: readonly ConditionBranch[] = ["true", "false"];

export interface TriggerNode {
  id: WorkflowNodeId;
  type: "trigger";
  position: NodePosition;
  data: {
    label: string;
    description?: string;
    config: TriggerConfig;
  };
}

export interface ActionNode {
  id: WorkflowNodeId;
  type: "action";
  position: NodePosition;
  data: {
    label: string;
    description?: string;
    config: ActionConfig;
  };
}

export interface ConditionNode {
  id: WorkflowNodeId;
  type: "condition";
  position: NodePosition;
  data: {
    label: string;
    description?: string;
    config: ConditionConfig;
  };
}

export type WorkflowNode = TriggerNode | ActionNode | ConditionNode;
/** A directed connection describing flow from one node to another. */
export interface WorkflowEdge {
  id: WorkflowEdgeId;
  source: WorkflowNodeId;
  target: WorkflowNodeId;
  /**
   * Which of a Condition node's outputs this edge leaves from. Undefined for
   * trigger and action sources, which have a single unnamed output.
   */
  sourceHandle?: ConditionBranch;
  /** Optional display caption drawn on the edge. */
  label?: string;
}

/** A complete, persistable workflow document. */
export interface Workflow {
  id: WorkflowId;
  name: string;
  description?: string;
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
  createdAt: IsoDateString;
  updatedAt: IsoDateString;
}

/* ------------------------------------------------------------------------
 * Execution
 *
 * A run walks a Workflow's graph and records what happened at each node it
 * reached. Nothing here is generated by pure domain logic (no id, no
 * timestamp) -- constructing a real WorkflowRun, like constructing a real
 * WorkflowNode, is the store's job. See workflowStore.ts's use of
 * crypto.randomUUID()/now() for the equivalent pattern on the document
 * side.
 * ------------------------------------------------------------------------ */

/** Identifier of a {@link WorkflowRun}. */
export type WorkflowRunId = string;

/**
 * How one node's step resolved during a run.
 *
 * There is no "running" state: a run is synchronous today, so every node's
 * result exists the instant the run returns -- there's no in-between
 * moment for "running" to describe. It would become meaningful only if a
 * later phase animates steps one at a time with real delays between them.
 */
export type NodeRunStatus = "success" | "failure" | "skipped";

/** What happened at one node during a run. */
export interface NodeRunResult {
  nodeId: WorkflowNodeId;
  status: NodeRunStatus;
  /** Human-readable explanation, e.g. why a branch was or wasn't taken. */
  detail: string;
}

/** A complete record of one execution of a {@link Workflow}. */
export interface WorkflowRun {
  id: WorkflowRunId;
  startedAt: IsoDateString;
  finishedAt: IsoDateString;
  /** In the order nodes were actually reached. */
  steps: NodeRunResult[];
}
